# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gameUI2048.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 173)
        Form.setStyleSheet("background-color: rgb(250, 248, 239);\n"
"")
        self.overallLayout = QtWidgets.QVBoxLayout(Form)
        self.overallLayout.setObjectName("overallLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("color: rgb(119, 110, 101);\n"
"font: 666 48pt \"Gadugi\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setStyleSheet("background-color: rgb(187, 173, 160);\n"
"border-radius: 5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_score = QtWidgets.QLabel(self.frame)
        self.title_score.setStyleSheet("font: 666 10pt \"Arial\";\n"
"color: rgb(238, 228, 214);")
        self.title_score.setObjectName("title_score")
        self.verticalLayout_2.addWidget(self.title_score, 0, QtCore.Qt.AlignHCenter)
        self.score_label = QtWidgets.QLabel(self.frame)
        self.score_label.setStyleSheet("font: 87 16pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.score_label.setObjectName("score_label")
        self.verticalLayout_2.addWidget(self.score_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setStyleSheet("background-color: rgb(187, 173, 160);\n"
"border-radius: 5px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_best = QtWidgets.QLabel(self.frame_2)
        self.title_best.setStyleSheet("font: 666 10pt \"Arial\";\n"
"color: rgb(238, 228, 214);")
        self.title_best.setObjectName("title_best")
        self.verticalLayout_3.addWidget(self.title_best, 0, QtCore.Qt.AlignHCenter)
        self.best_score_label = QtWidgets.QLabel(self.frame_2)
        self.best_score_label.setStyleSheet("font: 87 16pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.best_score_label.setObjectName("best_score_label")
        self.verticalLayout_3.addWidget(self.best_score_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.frame_2)
        self.overallLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("font: 12pt \"Gadugi\";\n"
"color: rgb(119, 110, 101);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.new_game_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_game_btn.sizePolicy().hasHeightForWidth())
        self.new_game_btn.setSizePolicy(sizePolicy)
        self.new_game_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.new_game_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.new_game_btn.setStyleSheet("QPushButton {\n"
"    font: 888 10pt \"Arial\";\n"
"    background-color: rgb(143, 122, 102);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #665e55;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #554e45;\n"
"}")
        self.new_game_btn.setObjectName("new_game_btn")
        self.horizontalLayout_2.addWidget(self.new_game_btn)
        self.overallLayout.addLayout(self.horizontalLayout_2)
        self.board_widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.board_widget.sizePolicy().hasHeightForWidth())
        self.board_widget.setSizePolicy(sizePolicy)
        self.board_widget.setStyleSheet("background-color: rgb(187, 173, 160);\n"
"border-radius: 5px;")
        self.board_widget.setObjectName("board_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.board_widget)
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.overallLayout.addWidget(self.board_widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Form", "2048"))
        self.title_score.setText(_translate("Form", "SCORE"))
        self.score_label.setText(_translate("Form", "0"))
        self.title_best.setText(_translate("Form", "BEST"))
        self.best_score_label.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Play 2048 Game Online</span><br/>Join the numbers and get to the <span style=\" font-weight:600;\">2048 tile!</span></p></body></html>"))
        self.new_game_btn.setText(_translate("Form", "New Game"))
